name: signage_android_player
description: "Signage Android Player application"
publish_to: 'none'

version: 1.1.2+3

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path_provider: ^2.1.4
  crypto: ^3.0.5
  video_player: ^2.9.2
  device_info_plus: ^12.3.0
  shared_preferences: ^2.3.2
  wakelock_plus: ^1.2.8
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

